name: Publish Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write

jobs:
  build_python_tts:
    name: Push python-tts Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          context: .
          file: docker/python-tts/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/speech-tools:python-tts
            ghcr.io/cmahnke/speech-tools:latest

  build_python_tts_models:
    name: Push python-tts Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: build_python_tts

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          context: .
          file: docker/python-tts/Dockerfile.models
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/speech-tools:python-tts-models

  build_piper:
    name: Push piper Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          context: .
          file: docker/piper/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/speech-tools:piper

  build_piper_models:
    name: Push piper Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: build_piper

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          context: .
          file: docker/piper/Dockerfile.models
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/speech-tools:piper-models
